/**
 * app/layout.js — Next.js Root Layout
 *
 * Wraps every page in the application with:
 *   - ClerkProvider    : makes Clerk auth context available client-side
 *   - ThemeProvider    : enables dark/light/system theme (next-themes via shadcn)
 *   - Toaster          : global sonner toast notification container
 *   - Google Fonts     : Geist Sans, Geist Mono, Outfit loaded via next/font
 *
 * suppressHydrationWarning on <html> is required by next-themes to avoid a
 * React hydration mismatch when applying the stored theme class on first render.
 */
import { Geist, Geist_Mono, Outfit } from "next/font/google";
import "./globals.css";
import { ClerkProvider } from "@clerk/nextjs";
import { Toaster } from "@/components/ui/sonner";
import { ThemeProvider } from "@/components/ThemeProvider";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});
 
const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

const outfit= Outfit({
  variable: "--font-outfit",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
     <ClerkProvider>
    <html lang="en" suppressHydrationWarning>
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
        <ThemeProvider attribute="class" defaultTheme="system" enableSystem disableTransitionOnChange>
          <Toaster />
          {children}
        </ThemeProvider>
      </body>
    </html>
    </ClerkProvider>
  );
}
